/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HealthWalletConsentInterface extends Interface {
    getFunction(nameOrSignature: "access" | "addDocument" | "checkAccess" | "documentCount" | "documents" | "grantAccess" | "revokeAccess"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "AccessRevoked" | "DocumentAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'access', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'addDocument', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'checkAccess', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'documentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'documents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantAccess', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeAccess', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'access', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'documentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'documents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAccess', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [docId: BigNumberish, provider: AddressLike, expiry: BigNumberish];
      export type OutputTuple = [docId: bigint, provider: string, expiry: bigint];
      export interface OutputObject {docId: bigint, provider: string, expiry: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRevokedEvent {
      export type InputTuple = [docId: BigNumberish, provider: AddressLike];
      export type OutputTuple = [docId: bigint, provider: string];
      export interface OutputObject {docId: bigint, provider: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DocumentAddedEvent {
      export type InputTuple = [docId: BigNumberish, patient: AddressLike, hash: string];
      export type OutputTuple = [docId: bigint, patient: string, hash: string];
      export interface OutputObject {docId: bigint, patient: string, hash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HealthWalletConsent extends BaseContract {
    
    connect(runner?: ContractRunner | null): HealthWalletConsent;
    waitForDeployment(): Promise<this>;

    interface: HealthWalletConsentInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    access: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[boolean, bigint] & {granted: boolean, expiry: bigint }],
      'view'
    >
    

    
    addDocument: TypedContractMethod<
      [_patient: AddressLike, _hash: string, ],
      [void],
      'nonpayable'
    >
    

    
    checkAccess: TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    documentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    documents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string] & {patient: string, hash: string }],
      'view'
    >
    

    
    grantAccess: TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAccess: TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'access'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[boolean, bigint] & {granted: boolean, expiry: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'addDocument'): TypedContractMethod<
      [_patient: AddressLike, _hash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkAccess'): TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'documentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'documents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string] & {patient: string, hash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccess'): TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAccess'): TypedContractMethod<
      [docId: BigNumberish, provider: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'AccessRevoked'): TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
getEvent(key: 'DocumentAdded'): TypedContractEvent<DocumentAddedEvent.InputTuple, DocumentAddedEvent.OutputTuple, DocumentAddedEvent.OutputObject>;

    filters: {
      
      'AccessGranted(uint256,address,uint256)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'AccessRevoked(uint256,address)': TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
      AccessRevoked: TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
    

      'DocumentAdded(uint256,address,string)': TypedContractEvent<DocumentAddedEvent.InputTuple, DocumentAddedEvent.OutputTuple, DocumentAddedEvent.OutputObject>;
      DocumentAdded: TypedContractEvent<DocumentAddedEvent.InputTuple, DocumentAddedEvent.OutputTuple, DocumentAddedEvent.OutputObject>;
    
    };
  }