/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Counter__factory } from './Counter__factory.js';
export { HealthWalletConsent__factory } from './HealthWalletConsent__factory.js';